DROP TABLE IF EXISTS localNews.articles;

DROP SCHEMA IF EXISTS localNews CASCADE;

CREATE SCHEMA IF NOT EXISTS localNews;

CREATE TABLE IF NOT EXISTS localNews.articles(
    entryId BIGSERIAL CONSTRAINT art_pk PRIMARY KEY,
    source VARCHAR(6) DEFAULT NULL,
    title VARCHAR(2048) DEFAULT NULL,
    subTitle VARCHAR(2048) DEFAULT NULL,
    author VARCHAR(2048) DEFAULT NULL,
    article TEXT DEFAULT NULL,
    publishedDate VARCHAR(256) DEFAULT NULL,
    parseddate TIMESTAMP(0) DEFAULT NULL,
    link TEXT NOT NULL,
    tags VARCHAR(2048) DEFAULT NULL
);